app:
  schema-name: &schema-name time_tracker_schema
spring:
  application:
    name: FirstPetProjectTimeTracker

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

      ddl-auto: validate
    properties:
      hibernate:
        default_schema: *schema-name

  liquibase:
    change-log: classpath:/db/changelog/db/changelog-master.yaml
    default-schema: *schema-name
#    enabled: false

  datasource:
    url: jdbc:postgresql://postgres:5432/mydb?currentSchema=time_tracker_schema
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: 8080